<a href="https://colab.research.google.com/github/ishaan0013/Udemy_ML_CourseWork/blob/main/Copy_of_data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

## Importing the dataset

In [3]:
dataset = pd.read_csv("Data.csv")
feature_dataset = dataset.iloc[:, :-1].values #iloc is located indexes, first row then column
dependent_variable = dataset.iloc[:, -1].values #Y

In [4]:
print(feature_dataset)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [5]:
print(dependent_variable)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(feature_dataset[:,1:3])
feature_dataset[:,1:3]=imputer.transform(feature_dataset[:,1:3])

In [7]:
print(feature_dataset)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct =ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough') #first arg-> which transformation we have to do and in which index of column, second arg->we need column that dont transform
feature_dataset=np.array(ct.fit_transform(feature_dataset)) #

In [13]:
print(feature_dataset)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [14]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()
dependent_variable=le.fit_transform(dependent_variable)

In [15]:
print(dependent_variable)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [16]:
from sklearn.model_selection import train_test_split
X_Train,X_Test,Y_Train,Y_Test= train_test_split(feature_dataset,dependent_variable,test_size=0.2,random_state=1)

In [18]:
print(X_Train  )
print(X_Test )
print(Y_Train  )
print(Y_Test)

[[1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]]
[[1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]
[0 1 0 0 1 1 0 1]
[0 1]


## Feature Scaling

In [19]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_Train[:,4:]=sc.fit_transform(X_Train[:,4:])
X_Test[:,4:]=sc.transform(X_Test[:,4:])


In [20]:
print(X_Train)
print(X_Test)

[[1.0 0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [1.0 0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [0.0 1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [1.0 0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [1.0 0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [0.0 1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [1.0 0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [0.0 1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]
[[1.0 0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [0.0 1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
